version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - EDIBLE_MODEL_PATH=/app/models/edible_detector.h5
      - SPECIES_MODEL_PATH=/app/models/species_detector.h5
    networks:
      - shroom-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - shroom-network

networks:
  shroom-network:
    driver: bridge