import os

ORIGINAL_EDIBLE_IMAGES_GCP_BUCKET_NAME = os.environ.get("ORIGINAL_EDIBLE_IMAGES_GCP_BUCKET_NAME")
ORIGINAL_KAGGLE_IMAGES_GCP_BUCKET_NAME = os.environ.get("ORIGINAL_KAGGLE_IMAGES_GCP_BUCKET_NAME")
RESIZED_KAGGLE_IMAGES_GCP_BUCKET_NAME = os.environ.get("RESIZED_KAGGLE_IMAGES_GCP_BUCKET_NAME")
